name: IG Build

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"

      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2"

      - run: npm install -g fsh-sushi

      - name: Download IG Publisher
        run: |
          mkdir -p input-cache
          curl -fsSL \
            https://github.com/HL7/fhir-ig-publisher/releases/download/${IG_PUBLISHER_VERSION/publisher.jar \
            -o input-cache/publisher.jar

      - run: sushi . --log-level info

      - name: Build IG
        run: |
          java -jar input-cache/publisher.jar \
            -ig . \
            -tx https://tx.fhirlab.net/fhir \
            -cachedir ~/.fhir/packages \
            -txCache input-cache/txcache

      - uses: actions/upload-artifact@v4
        with:
          name: ig-output
          path: output